### ISSUE TITLE
npm packages incomplete

### ISSUE THREAD

**Issue by martinLE** [adeperio/base#60]
The `package.json` file is incomplete. After running `npm install` and `gulp bootsrap`, trying to start with `gulp` will throw errors. These packages are missing:
* browserslist
* num2fraction
* caniuse-db
* postcss

**Comment by adeperio** [comment]
Awesome thanks Martin, I'm looking into these issues this week, will get your PR integrated...

**Comment by adeperio** [comment]
Hi @martinLE , sorry this is a super late reply, been crazy busy on my end. Been hard to find the time the past month to look into some of these issues. Thanks again for the PR, just merged this in and doing some last cursory checks on the dependency problem
