### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by kyle-rader** [adeperio/base#64]
Hi, 

I am really excited to have found your starter kit.  It most closely resembles the structure of a React App I wanted to build (particularly the emphasis on security).  However, I've run into several major difficulties trying to get this up and running that hopefully you can speak to and/or add instruction to the README to address.

1. You cannot use Node 4.1.1 and `npm install` all of the dependencies of the project.  `contextify` will fail to build - I could not find any solutions and finally after downgrading to v0.12.7 was able to install dependencies.
2.  Having to setup apps on Facebook and/or Google to work with basic auth seems tedious and like a high barrier to entry.  This isn't my first go at it, but I remember my first go and I can easily see it being a point of frustration.  
3. If you copy the `sample.env` and leave in the `PORT=3000` you would think your app is running on port 3000, but when you run gulp, it logs as saying the app is running on 3001 and that browser sync is running on 3002.  Browser sync was in fact on 3002 but the app was actually on 3000.  This discrepancy through me off for a while and still may be the source of 4 and 5.
4. If I go to the port gulp says the app is running on, it doesn't just ignore it.  The server never actually responds it just hangs (curl will literally never return).  Something is afoot!? 
4. Now that I am trying to access the site on the right port, none of the assets are downloading, only the initial html with a container waiting to be replaced by React.  This is where I am currently debugging.

Any info would be great.  

I am running the setup on my local server (Ubuntu 14.04), accessing from my Windows machine on the network.  I've changed the hosts file on my Windows machine to point to the local server, and the local server to point to itself (faking real TLD's for the auth callbacks). 

Cheers,
Kyle W. Rader (kyle.rader@ieee.org)

**Comment by kyle-rader** [comment]
@adeperio Update:  I've just got it working! Hurray!  I will now start hacking and if I see an opportunity to do something on the ToDo List I'll try to do so.  I ended up using the proxy address to get around browser restrictions I am still digging through the code to see why it won't connect to browser sync on the normal port.  In several includes I found typos leading to "Could not find module" errors - pull request incoming. 

Cheers,
Kyle W. Rader

**Comment by adeperio** [comment]
Heya @kyle-rader 

Nice spots, and thanks for sending those through! A lot of those issues are on my radar as well so just trying to wrangle the time to have a look into them on my end :) A yeoman generator is on top of the priorities list or at the very least an easier install procedure. The installation process has a lot of moving manual parts at the moment that need to evolve into automating as much of the Auth and SSL setups as we can, but we'll get there :) 

The port number that's specified in your .env file (re: config.js) is actually being referenced at the moment and is being pulled from process.env.PORT. Confusing I know so will look into this too ...

Had a few people bring up the dependency problem as well so trying to get this rectified. 

Thanks for having a look! Hope you are able move forward a little with the repo in your own projects, throw up an issue here or send me a message if you hit any more blockers :) 

And by all means feel free to pick up some of the open issues :) This is a young repo so any help is super useful!

**Comment by kyle-rader** [comment]
@adeperio Sounds great, thanks for the quick response!

**Comment by adeperio** [comment]
No worries @kyle-rader.

One other thing, the node version at the moment that Base is using is 0.12.5, so there's work to do to upgrade the node version as well. Hence why you're having problems with pulling down the deps. You can use nvm to set the node version  to 0.12.5 for now. WIll throw up an issue to upgrade Node.

**Comment by adeperio** [comment]
Hey Kyle, its been ages since being able to work on Base, but will be doing quite a few changes on this in the next coming months. FYI we've upgraded to Node 5.6.0 which should keep it up to date wiht security fixes :)
